platform :ios, '9.0'

target 'BuddyV2' do
use_frameworks!

pod 'Firebase/Core'
pod 'Firebase/Storage'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'JSQMessagesViewController'
pod 'SwiftyJSON', '~> 4.0'
pod 'SwiftInstagram', '~> 1.1.1'

end
